---
 - hosts: all
   become: yes
   roles:
     - { role: influxdb, tags: influxdb }
     - { role: grafana, tags: grafana }
     - { role: telegraf, tags: telegraf }
     - { role: kapacitor, tags: kapacitor }
