---

- meta: flush_handlers

- name: Unarchive Kafka tarball
  unarchive: src="kafka_{{kafka_version}}.tgz" dest="{{kafka_dir}}"

- name: Configure Kafka
  template: >
    src=server.properties.j2
    dest="{{kafka_dir}}/kafka_{{kafka_version}}/config/server.properties"
    owner=root
    group=root
    mode=0644

- name: Create init.d script for Kafka
  template: >
    src=kafka.j2
    dest=/etc/init.d/kafka
    owner=root
    group=root
    mode=0755
  notify: start kafka